# Robin base URL. Update the IP before launching any of the requests.
@robinBaseUrl = http://10.244.0.32:8080

# Metrics

###

GET {{robinBaseUrl}}/metrics

# RedisCluster

## Status

###

GET {{robinBaseUrl}}/v1/redkeycluster/status

###

PUT {{robinBaseUrl}}/v1/redkeycluster/status

{
    "status": "Ready"
}

## Replicas

###

GET {{robinBaseUrl}}/v1/redkeycluster/replicas

###

PUT {{robinBaseUrl}}/v1/redkeycluster/replicas

{
    "replicas": 6,
    "replicas_per_master": 0
}

## Cluster

### Status

GET {{robinBaseUrl}}/v1/cluster/status

### Check

GET {{robinBaseUrl}}/v1/cluster/check

### Nodes

GET {{robinBaseUrl}}/v1/cluster/nodes

### Fix

PUT {{robinBaseUrl}}/v1/cluster/fix

### Move

PUT {{robinBaseUrl}}/v1/cluster/move

{
    "from": "4",
    "to": "5",
    "slots": 0
}

### ResetNode

@nodeIndex = 6
PUT {{robinBaseUrl}}/v1/cluster/reset/{{nodeIndex}}
