# SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: redkey-cluster
description: A Helm chart for deploying a RedkeyCluster custom resource
type: application
version: 0.1.0
appVersion: "0.1.0"
