// SPDX-FileCopyrightText: 2025 INDUSTRIA DE DISEÑO TEXTIL, S.A. (INDITEX, S.A.)
//
// SPDX-License-Identifier: Apache-2.0

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pdb) DeepCopyInto(out *Pdb) {
	*out = *in
	out.PdbSizeUnavailable = in.PdbSizeUnavailable
	out.PdbSizeAvailable = in.PdbSizeAvailable
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pdb.
func (in *Pdb) DeepCopy() *Pdb {
	if in == nil {
		return nil
	}
	out := new(Pdb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisAuth) DeepCopyInto(out *RedisAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisAuth.
func (in *RedisAuth) DeepCopy() *RedisAuth {
	if in == nil {
		return nil
	}
	out := new(RedisAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (redkeyCluster *RedkeyCluster) DeepCopyInto(out *RedkeyCluster) {
	*out = *redkeyCluster
	out.TypeMeta = redkeyCluster.TypeMeta
	redkeyCluster.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	redkeyCluster.Spec.DeepCopyInto(&out.Spec)
	redkeyCluster.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyCluster.
func (redkeyCluster *RedkeyCluster) DeepCopy() *RedkeyCluster {
	if redkeyCluster == nil {
		return nil
	}
	out := new(RedkeyCluster)
	redkeyCluster.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (redkeyCluster *RedkeyCluster) DeepCopyObject() runtime.Object {
	if c := redkeyCluster.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedkeyClusterList) DeepCopyInto(out *RedkeyClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedkeyCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyClusterList.
func (in *RedkeyClusterList) DeepCopy() *RedkeyClusterList {
	if in == nil {
		return nil
	}
	out := new(RedkeyClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedkeyClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedkeyClusterOverrideSpec) DeepCopyInto(out *RedkeyClusterOverrideSpec) {
	*out = *in
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(appsv1.StatefulSet)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(corev1.Service)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyClusterOverrideSpec.
func (in *RedkeyClusterOverrideSpec) DeepCopy() *RedkeyClusterOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(RedkeyClusterOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobinSpec) DeepCopyInto(out *RobinSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyClusterOverrideSpec.
func (in *RobinSpec) DeepCopy() *RobinSpec {
	if in == nil {
		return nil
	}
	out := new(RobinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (redkeyClusterSpec *RedkeyClusterSpec) DeepCopyInto(out *RedkeyClusterSpec) {
	*out = *redkeyClusterSpec
	out.Auth = redkeyClusterSpec.Auth
	if redkeyClusterSpec.Robin != nil {
		in, out := &redkeyClusterSpec.Robin, &out.Robin
		*out = new(RobinSpec)
		(*in).DeepCopyInto(*out)
	}
	if redkeyClusterSpec.Resources != nil {
		in, out := &redkeyClusterSpec.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if redkeyClusterSpec.Labels != nil {
		in, out := &redkeyClusterSpec.Labels, &out.Labels
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	out.Pdb = redkeyClusterSpec.Pdb
	if redkeyClusterSpec.AccessModes != nil {
		in, out := &redkeyClusterSpec.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if redkeyClusterSpec.Override != nil {
		in, out := &redkeyClusterSpec.Override, &out.Override
		*out = new(RedkeyClusterOverrideSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyClusterSpec.
func (redkeyClusterSpec *RedkeyClusterSpec) DeepCopy() *RedkeyClusterSpec {
	if redkeyClusterSpec == nil {
		return nil
	}
	out := new(RedkeyClusterSpec)
	redkeyClusterSpec.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedkeyClusterStatus) DeepCopyInto(out *RedkeyClusterStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]*RedisNode, len(*in))
		for key, val := range *in {
			var outVal *RedisNode
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RedisNode)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedkeyClusterStatus.
func (in *RedkeyClusterStatus) DeepCopy() *RedkeyClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RedkeyClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisNode) DeepCopyInto(out *RedisNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisNode.
func (in *RedisNode) DeepCopy() *RedisNode {
	if in == nil {
		return nil
	}
	out := new(RedisNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlotRange) DeepCopyInto(out *SlotRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotRange.
func (in *SlotRange) DeepCopy() *SlotRange {
	if in == nil {
		return nil
	}
	out := new(SlotRange)
	in.DeepCopyInto(out)
	return out
}
