apiVersion: redkey.inditex.dev/v1
kind: RedkeyCluster
metadata:
  name: {{ include "redkey-cluster.name" . }}
  labels:
    {{- include "redkey-cluster.labels" . | nindent 4 }}
spec:
  primaries: {{ .Values.primaries }}
  replicasPerPrimary: {{ .Values.replicasPerPrimary }}
  ephemeral: {{ .Values.ephemeral }}
  {{- if .Values.purgeKeysOnRebalance }}
  purgeKeysOnRebalance: {{ .Values.purgeKeysOnRebalance }}
  {{- end }}
  image: {{ .Values.image }}
  {{- if and (not .Values.ephemeral) .Values.storage }}
  storage: {{ .Values.storage }}
  {{- end }}
  {{- if and (not .Values.ephemeral) .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.accessModes | nindent 4 }}
  {{- if .Values.deletePVC }}
  deletePVC: {{ .Values.deletePVC }}
  {{- end }}
  {{- if .Values.backup }}
  backup: {{ .Values.backup }}
  {{- end }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.config }}
  config: |
    {{- .Values.config | nindent 4 }}
  {{- end }}
  {{- if .Values.resources }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  {{- end }}
  robin:
    config:
      {{- toYaml .Values.robin.config | nindent 6 }}
    template:
      spec:
        containers:
          - image: {{ .Values.robin.image }}
            name: robin
            imagePullPolicy: {{ .Values.robin.imagePullPolicy }}
            ports:
              - containerPort: 8080
                name: prometheus
                protocol: TCP
            volumeMounts:
              - mountPath: /opt/conf/configmap
                name: {{ include "redkey-cluster.name" . }}-robin-config
            {{- if .Values.robin.resources }}
            resources:
              {{- toYaml .Values.robin.resources | nindent 14 }}
            {{- end }}
        volumes:
          - configMap:
              defaultMode: 420
              name: {{ include "redkey-cluster.name" . }}-robin
            name: {{ include "redkey-cluster.name" . }}-robin-config
